### PR TITLE
Add <cstdint> to Pipe.cpp

### PR DESCRIPTION
**Pull request by rshym**
The yocto scarthgap uses GCC 13, and according to the manual 'Porting to GCC 13', some headers need to be included explicitly. Without the explicit inclusion of the `cstdint` we will have a build error 'uint8_t is not defined' on the scarthgap.

### CODE REVIEW

**Comment by rshym** [comment]
Successfully compiled under GCC 11 (kirkstone) and GCC 13 (scarthgap).

Link to the [Porting to GCC 13](https://gcc.gnu.org/gcc-13/porting_to.html). Info mentioned in the commit is in the first block "Header dependency changes".

**Comment by rshym** [comment]
@lorc could you please take a look?

**Review by lorc — APPROVED** [review]
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by rshym** [comment]
`Ack` was added. Tested.
Ready to be merged.
Thanks to the fixed commit of the libxenbe in the release v0.1.0 of the meta-xt-common, we are good to merge and will not break existing projects.

**Pull request merged**
